# -*- coding: utf-8 -*-
"""Counting_holes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NsfglrWmsaZZ-QbaSRwRqOaYadb80KCi
"""

import cv2

from matplotlib import pyplot as plt

"""#Loaded Image

"""

img = cv2.imread('/content/test7.jpg')

"""#Converted to grayscale"""

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

gray

plt.imshow(gray)

"""#Applying Noise Reduction"""

blur = cv2.GaussianBlur(img, (5, 5), 0)

"""#Thresholding"""

ret, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

ret

binary

"""#Contour's"""

contours, ret = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

contours

ret

"""#Filter the contour's"""

min_area_threshold = 100
filtered_contours = [cnt for cnt in contours if cv2.contourArea(cnt) > min_area_threshold]

"""#Counting Holes"""

hole_count = len(filtered_contours)

from google.colab.patches import cv2_imshow
cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

print('Number of Holes:', hole_count)

